#!/bin/bash
#
# There are two different environments we need to support:
#   - kernel -- for anything needed by the notebook code itself (py2)
#   - notebook -- for anything used by the Jupyter framework (py3)
#

# configure to allow conda from terminal (we don't have an interactive one
# during docker image build, so don't have .bashrc)
conda init bash
. .bashrc

# We need ipywidgets for our notebook
# (could be moved to requirements.txt, but want to keep that CLI only for now)
conda activate kernel
conda install -y -c conda-forge ipywidgets

# We need to install the rest into the server's environment.
conda activate notebook
conda install -y -c conda-forge jupyter_contrib_nbextensions

### ones we need for sure
##- "initialization cells" aka 'init_cell'
jupyter nbextension enable init_cell/main
jupyter nbextension enable collapsible_headings/main
##
### maybe add
##- "Select CodeMirror Keymap" aka "select_keymap"
##- "Tree Filter" aka "tree-filter"
##- "Codefolding in Editor" aka "codefolding"
##- "Collapsible Headings" aka "collapsible_headings"
#jupyter labextension list --help-all
#jupyter labextension enable init_cell
##
### debug help
##- "Nbextensions edit menu item" aka "nbextensions_configurator"
##- "contrib_nbextensions_help_item"
