#!/bin/bash -i
# N.B.  the '-i' above is required to fake an interactive shell
#       the default .bashrc bails if not interactive, but we need
#       conda's "activate" command to work, which is enabled via .bashrc
echo "At start: $-"
case "$-" in
  *i*)  ;;
  *)    echo "must run as interactive shell"
        exit 3
        ;;
esac
#
# There are two different environments we need to support:
#   - kernel -- for anything needed by the notebook code itself
#   - notebook -- for anything used by the Jupyter framework
#

# We're started in the kernel's environment, so do items needed for that
# (could be moved to requirements.txt)
conda install -c conda-forge ipywidgets

# We need to install the rest into the notebook's environment.
conda init bash
. .bashrc
conda activate notebook
conda install -c conda-forge jupyter_contrib_nbextensions

### ones we need for sure
##- "initialization cells" aka 'init_cell'
jupyter nbextension enable init_cell/main
jupyter nbextension enable collapsible_headings/main
##
### maybe add
##- "Select CodeMirror Keymap" aka "select_keymap"
##- "Tree Filter" aka "tree-filter"
##- "Codefolding in Editor" aka "codefolding"
##- "Collapsible Headings" aka "collapsible_headings"
#jupyter labextension list --help-all
#jupyter labextension enable init_cell
##
### debug help
##- "Nbextensions edit menu item" aka "nbextensions_configurator"
##- "contrib_nbextensions_help_item"
